## 1.Library

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

import os
import numpy as np
import sys
sys.path.append('../') # these two lines allow the notebook to find the path to the source code contained in 'src'
from src.descriptors import color_histogram, calculate_color_histogram_all, lbp_histogram, merging_descriptors
from src.pipeline import pipeline_histogram_joint

In [2]:
path_file_label = "../data/caltech101_subset.files"
path_file_images =  "../data/caltech101_subset"

## 2. Colors histogram

In [3]:
X_colors, y_colors = calculate_color_histogram_all(path_file_label,path_file_images,
                                     func_histogram=color_histogram, bins_per_channel=8)

In [4]:
X_colors.shape , y_colors.shape

((1000, 512), (1000,))

In [5]:
set(y_colors)

{np.str_('Faces_easy'),
 np.str_('Leopards'),
 np.str_('Motorbikes'),
 np.str_('airplanes'),
 np.str_('bonsai'),
 np.str_('car_side'),
 np.str_('chandelier'),
 np.str_('hawksbill'),
 np.str_('ketch'),
 np.str_('watch')}

In [6]:
lg_model = LogisticRegression()
pipeline_histogram_joint(X_colors,y_colors,lg_model, 0.2 , 42)

(LogisticRegression(),
 0.545,
 array([[18,  1,  0,  0,  0,  0,  0,  1,  0,  0],
        [ 0, 13,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  1, 20,  2,  1,  0,  0,  2,  1,  0],
        [ 0,  1,  4,  8,  0,  0,  0,  1,  5,  2],
        [ 1,  3,  3,  1,  1,  0,  2,  2,  2,  0],
        [ 0,  0,  0,  0,  0, 22,  0,  0,  0,  0],
        [ 4,  1,  0,  1,  0,  4,  7,  5,  2,  1],
        [ 0,  1,  0,  1,  2,  0,  0,  8,  1,  0],
        [ 2,  0,  2,  0,  0,  0,  1,  6, 11,  1],
        [ 2,  2,  9,  1,  0,  2,  0,  3,  1,  1]]))

## 3. LBP histogram

In [7]:
X_lbp, y_lbp = calculate_color_histogram_all(path_file_label,path_file_images,
                                     func_histogram=lbp_histogram, P=8, R=1, method='uniform')

In [8]:
lg_model = LogisticRegression()
pipeline_histogram_joint(X_lbp, y_lbp, lg_model, 0.2 , 42)

(LogisticRegression(),
 0.345,
 array([[17,  2,  0,  1,  0,  0,  0,  0,  0,  0],
        [ 1, 10,  0,  1,  0,  0,  0,  1,  0,  0],
        [ 1,  2, 20,  1,  3,  0,  0,  0,  0,  0],
        [ 3,  0,  4, 14,  0,  0,  0,  0,  0,  0],
        [ 1,  5,  3,  0,  1,  1,  0,  2,  0,  2],
        [ 6, 11,  0,  0,  0,  4,  0,  1,  0,  0],
        [ 1,  7,  6,  8,  0,  0,  0,  2,  0,  1],
        [ 3,  5,  0,  1,  1,  1,  0,  1,  0,  1],
        [ 5,  5,  4,  4,  2,  2,  0,  1,  0,  0],
        [ 3,  6,  7,  1,  2,  0,  0,  0,  0,  2]]))

## 4.Combining descriptors

In [9]:
X_fused = merging_descriptors(X_desc1=X_colors, X_desc2=X_lbp)
y_fused = y_colors.copy()

X_fused.shape, y_fused.shape

((1000, 522), (1000,))

In [10]:
lg_model = LogisticRegression()
pipeline_histogram_joint(X_fused, y_fused, lg_model, 0.2 , 42)

(LogisticRegression(),
 0.57,
 array([[20,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0, 12,  0,  0,  0,  0,  0,  1,  0,  0],
        [ 1,  1, 20,  2,  1,  0,  0,  1,  1,  0],
        [ 1,  1,  3, 13,  0,  0,  0,  0,  3,  0],
        [ 1,  2,  3,  1,  1,  0,  2,  3,  2,  0],
        [ 0,  0,  0,  0,  0, 22,  0,  0,  0,  0],
        [ 2,  1,  0,  4,  1,  4,  7,  4,  2,  0],
        [ 0,  1,  0,  0,  3,  0,  0,  8,  1,  0],
        [ 3,  0,  2,  1,  1,  0,  2,  5,  9,  0],
        [ 4,  0,  7,  2,  0,  2,  0,  3,  1,  2]]))

In [11]:
X_colors.shape, X_lbp.shape

((1000, 512), (1000, 10))

## 5. Geometric segmentation of images